### ISSUE TITLE
Stackoverflow: external javascript is blocked

### ISSUE THREAD

**Issue by ghost** [jabbany/knProxy#11]
Hi @jabbany,

I've encountered an error message in SO where it says:
> Stack Overflow requires external JavaScript from another domain, which is blocked or failed to load.

Prior to that there was an alert saying:
> For security reasons: framing is not allowed.

Also, the navbar has disappeared.

**Comment by jabbany** [comment]
JS failing to load (unfortunately) is unavoidable since they probably are dynamically loading them and the proxy cannot capture requests sent from JS (because web proxies can't evaulate the JS and figure out what URLs will be requested to change them to point to th proxy instead).

As for the alert, some sites don't allow framing to prevent clickjacking. This is done in JS as well (so cannot be caught) in which case the navbar will not work due to the page trying to break out of the frame. The proxy should still work in such cases. Just that the navbar (being a frame) will not.

These are things that a web-proxy wouldn't be able to handle. To make this work you would need a proper HTTP or SOCKS proxy setup that pipes all requests/TCP connections.

**Comment by ghost** [comment]
thanks @jabbany, i'll look into your suggestion.

**Comment by jabbany** [comment]
Yeah. If you have a setup where you can install software (node, python etc.) I would recommend Shadowsocks. It's a SOCKS based TCP tunnel that can forward all requests (instead of having to rewrite the responses).
