### ISSUE TITLE
iframe inside site not working

### ISSUE THREAD

**Issue by carwirawan** [jabbany/knProxy#14]
Hi, i tried to open a site with iframe video with no luck
this one i tried to open is my own site
[http://01nonton.com/movies/nonton-the-perfection/](http://01nonton.com/movies/nonton-the-perfection/)

is there anyway i can fix this ? thanks

**Comment by jabbany** [comment]
The first step is to identify what part is not loading (e.g. is the iframe itself not working or is it the video inside). Based on that there may be different causes:

- If the iframe or video URL are loaded by a script (JS) dynamically, most likely the proxy will not work since the page is processed on the server side and knProxy can't execute scripts. You can check if this is the case by inspecting the network requests
- If the internals of the iframe do something with its url, the proxy may also not work as it rewrites the URL
- If the video is very large and the server side times out, the page data will load, just not the video. This is due to a limitation with the way PHP (specifically PHP5 when this was written) handles streams. The proxy has to fully download all the resources to rewrite the URLs in them, and large files or videos may not work properly if they time out server side. Especially if the remote server does not support HTTP ranges.

**Comment by carwirawan** [comment]
Hi thanks for the reply

wow.. its complicated
ok one last question, is it possible to use the proxy just for the main site, and let the iframe load from the original url ?

let say that the main site is abc.com and the iframe is iframe.com
can we setup abc.com to pass through proxy but iframe.com from its original url ?

Thanks

**Comment by jabbany** [comment]
It is possible to to do this with a couple of modifications (though it's not clear why you would want to only run the outer page through the proxy).

One method (if the iframe is only to a list of known domains) is to add a whitelist above [this line](https://github.com/jabbany/knProxy/blob/6b3c42fbc16e67e887ebec0b1a3e2fc82065a7ff/includes/module_parser.php#L258) and have a conditional whitelist based on the URL. You can match the URL and return the original url without running it through toAbsoluteUrl.

Another method that's more involved but can instead handle iframes regardless of the frame URL is to add a match in [this method](https://github.com/jabbany/knProxy/blob/6b3c42fbc16e67e887ebec0b1a3e2fc82065a7ff/includes/module_parser.php#L226) similar to the check for `form`. Here you can add a check for `iframe` and then do something different when it matches (e.g. return the original tag as is)

**Comment by carwirawan** [comment]
Hello again
Thanks for the reply

sorry for keep asking you
since im new in this, can you please give me example for 1st or 2nd method ?

Many thanks

**Comment by jabbany** [comment]
For method 1, you would essentially replace that line with something like:
````PHP
$url_rebased = $this->url->getAbsolute($urlField)
// $url_rebased is going to be a fully qualified URL
if ( /* something */ ) {
    return $method . '=' . $delim . $url_rebased . '&uA=' . $delim . ' ';
} else {
    return $method . '=' . $delim . $this->toAbsoluteUrl($url) . '&uA=' . $delim . ' '; // Original line
}
````

In the `/* something */` part you would probably do some string check to whitelist the URL, like some string matching with a whitelisted host (via `strpos` or regex etc.) or you can throw it into a new `knUrl` object and extract the hostname and do matching on that.

The second method invoves basically copying the `if` block and adding it as an `elseif` block, fixing the regex to match on `iframe` instead of `form`. Then inside the `if` you could just return. E.g. :
````PHP
// end of if block before ...
elseif(preg_match('~^\s*iframe~iUs',$match[1])){
    return '<' . $match[1] . '>';
}
````

Note that method 1 disables proxying for a URL pattern (regardless of where it appears) and method 2 disables proxying of all iframes, regardless of where they lead to. To whitelist a pattern only when it's in an iframe, you would modify the method 2 code to then check the match and only return if the match also matches a URL pattern.

**Comment by carwirawan** [comment]
Hello again Jim
Thanks for the example, i ll ask someone to set it up for me
